<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.1.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Homepage Formular Übermittlung',
	'heading' => 'Neue Formularübermittlung',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Aktiviert',
		'checkbox_unchecked' => 'Nicht aktiviert',
		'submitted_from' => 'Von Website übermitteltes Formular: %s',
		'submitted_by' => 'Besucher-IP-Adresse: %s',
		'too_many_submissions' => 'Zu viele Sendungen in letzter Zeit von dieser IP',
		'failed_to_send_email' => 'E-Mail konnte nicht gesendet werden',
		'invalid_reCAPTCHA_private_key' => 'Ungültiger privater reCAPTCHA-Schlüssel.',
		'invalid_reCAPTCHA2_private_key' => 'Ungültiger privater reCAPTCHA 2.0-Schlüssel.',
		'invalid_reCAPTCHA2_server_response' => 'Ungültige private reCAPTCHA 2.0-Server-Reaktionszeit.',
		'invalid_field_type' => 'Unbekannter Feldtyp „%s“.',
		'invalid_form_config' => 'Die Konfiguration im Feld „%s“ ist ungültig.',
		'unknown_method' => 'Unbekannte Serveranfragemethode'
	),
	'email' => array(
		'from' => 'start@30watt.de',
		'to' => 'start@30watt.de'
	),
	'fields' => array(
		'custom_U882' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Name',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Name“ ist erforderlich.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'E-Mil',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „E-Mil“ ist erforderlich.',
				'format' => 'Die E-Mail-Adresse in Feld „E-Mil“ ist ungültig.'
			)
		),
		'custom_U892' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Nachricht',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U1055' => array(
			'order' => 4,
			'type' => 'checkbox',
			'label' => 'Ich habe die Datenschutz hinweise gelesen!',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Ich habe die Datenschutz hinweise gelesen!“ ist erforderlich.'
			)
		)
	)
);

process_form($form);
?>
